name: todo-list-dynamodb-app

on:
  push:
    branches:
      - hml    
      - develop
      - main

jobs:
  unit-tests:
    if: github.event.ref == 'refs/heads/develop'
    strategy:
      matrix:
        node: [18.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Setup DynamoDB Local
      uses: rrainn/dynamodb-action@v2.0.1
      with:
        dbPath: # undefined by default, if this is undefined inMemory will be used
        sharedDb: # undefined by default
        delayTransientStatuses: # undefined by default
        optimizeDbBeforeStartup: # undefined by default
        port: 8000
        cors: '*'
            
    - name: Install dependencies
      run: npm ci
  
    - name: Unit tests
      run: npm run test:ci:unit

    - name: Integration tests
      run: npm run test:integration
      
