name: todo-list-dynamodb-app

on:
  push:
    branches:
      - hml    
      - develop
      - main

jobs:
  Explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci
    
      - name: Unit tests
        run: npm run test:ci:unit
