name: todo-list-dynamodb-app

on:
  push:
    branches:
      - hml    
      - develop
      - main

jobs:
  Explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HELLO PIPELINE GO GO GO"